spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mall?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    url: jdbc:mysql://192.168.2.100:3306/mall?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
    username: root
#    password: lgl33926
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  servlet:
    multipart:
      max-file-size: 100MB # 单个文件大小
      max-request-size: 100MB # 设置总上传的数据大小
      enabled: true #开启
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
server:
  servlet:
    context-path: /
  port: 8084
logging:
  path: /spring/manage
  level:
    com:
      cskaoyan:
        wdjava:
          mapper: debug
wd:
   uploadPath: /usr/local/project1/
#      uploadPath: c:/usr/file/image/

img:
  urlIp: 192.168.2.100
#    urlIp: 192.168.0.102


